#import "FlutterNativeVisionCameraPlugin.h"

// Check for the existence of the modular Swift header.
// This is generated by Xcode when building the framework.
#if __has_include(<flutter_native_vision_camera/flutter_native_vision_camera-Swift.h>)
#import <flutter_native_vision_camera/flutter_native_vision_camera-Swift.h>
#else
#import "flutter_native_vision_camera-Swift.h"
#endif

@implementation FlutterNativeVisionCameraPlugin

+ (void)registerWithRegistrar:(NSObject<FlutterPluginRegistrar>*)registrar {
    // Relay the registration to the Swift implementation.
    // The Swift class was renamed to SwiftFlutterNativeVisionCameraPlugin 
    // to avoid name collision in the module map.
    [SwiftFlutterNativeVisionCameraPlugin registerWithRegistrar:registrar];
}

@end
